# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gshoot < Formula
  desc "Magically import/export CSVs from Google Sheets"
  homepage "https://github.com/gurgeous/gshoot"
  version "0.3.0"

  depends_on "openclaw/tap/gogcli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.3.0/gshoot_0.3.0_darwin_amd64.tar.gz"
      sha256 "90dda5e56be4c554f589d38a82887b1c8d97a40203b6e41b0bd1a90cc70e6d80"

      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.3.0/gshoot_0.3.0_darwin_arm64.tar.gz"
      sha256 "9f2268a80784f10fb7638a88402e62f85acdb54390f776c4bb152af2d209cbac"

      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.3.0/gshoot_0.3.0_linux_amd64.tar.gz"
      sha256 "41ba6c19dd95bce5a69dbb42d585cf7441769eef82cb743f87b009691fa56041"
      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.3.0/gshoot_0.3.0_linux_arm64.tar.gz"
      sha256 "11883a3b2589f02366a3219e513e79fc044178f75c8b065690acae926c74c45b"
      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
  end

  test do
    system "#{bin}/gshoot --version"
  end
end
