# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gshoot < Formula
  desc "Magically import/export CSVs from Google Sheets"
  homepage "https://github.com/gurgeous/gshoot"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.1.0/gshoot_0.1.0_darwin_amd64.tar.gz"
      sha256 "a9ec2ab826ebaa01d3b1541f136939afbce961e9435e5322a8c2ef115e4b9ab3"

      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.1.0/gshoot_0.1.0_darwin_arm64.tar.gz"
      sha256 "90fe1db1eab71b64b9da56de2b9b0b490822c645e4d96b581cc6625f886d8fef"

      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.1.0/gshoot_0.1.0_linux_amd64.tar.gz"
      sha256 "cd3f60679b601449a03a19e98ae2339e2b8f546fc58a4bb8fbe35187ff116e14"
      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.1.0/gshoot_0.1.0_linux_arm64.tar.gz"
      sha256 "cad5e2d4df6396ef01002f608b25d87e32eea12aaae629886a04372257a0deb4"
      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
  end

  test do
    system "#{bin}/gshoot --version"
  end
end
