# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gshoot < Formula
  desc "Magically import/export CSVs from Google Sheets"
  homepage "https://github.com/gurgeous/gshoot"
  version "0.2.0"

  depends_on "openclaw/tap/gogcli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.2.0/gshoot_0.2.0_darwin_amd64.tar.gz"
      sha256 "02903617b0b224ee6f603614c699849e4ae18bf70ce4e4641c1e6420e8b64c16"

      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.2.0/gshoot_0.2.0_darwin_arm64.tar.gz"
      sha256 "7c34275a6ef206ec29313cf8850d2d61115d37ad5025c68df6c96bea5c7688ce"

      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.2.0/gshoot_0.2.0_linux_amd64.tar.gz"
      sha256 "9b61f53df24e5de5a12de2074a35d8679aecdef8b0647f60528ef9adc525d17c"
      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/gshoot/releases/download/v0.2.0/gshoot_0.2.0_linux_arm64.tar.gz"
      sha256 "89b4a6470ad44ee31dc967c4756b91fe50b9cfda25b01fb811b44edc3dda627e"
      define_method(:install) do
        bin.install "gshoot"
        bash_completion.install "extra/gshoot.bash" => "gshoot"
        zsh_completion.install "extra/_gshoot" => "_gshoot"
      end
    end
  end

  test do
    system "#{bin}/gshoot --version"
  end
end
