# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tennis < Formula
  desc "Stylish CSV tables in your terminal."
  homepage "https://github.com/gurgeous/tennis"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/tennis/releases/download/v0.0.2/tennis_0.0.2_darwin_arm64.tar.gz"
      sha256 "6d362d99d8481fa2e44eca0d0c4e7ae76c0ac68395593efce9b517f9157f62b5"

      def install
        bin.install "tennis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/tennis/releases/download/v0.0.2/tennis_0.0.2_linux_amd64.tar.gz"
      sha256 "23d87431f8d9b2ebdccdcc94f711494ab8f873e2338377fbb03a6467779bb029"
      def install
        bin.install "tennis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/tennis/releases/download/v0.0.2/tennis_0.0.2_linux_arm64.tar.gz"
      sha256 "26f6aca5a20ca93df0036b9e992d77ee111f191f30db814da9de3f8fc70aa3f7"
      def install
        bin.install "tennis"
      end
    end
  end

  test do
    system "./tennis --version"
  end
end
