# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tennis < Formula
  desc "Stylish CSV tables in your terminal."
  homepage "https://github.com/gurgeous/tennis"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/tennis/releases/download/v0.1.0/tennis_0.1.0_darwin_arm64.tar.gz"
      sha256 "603e0acb64652179e5c1398e2a5a26dbb17516ff81b65fff093395527efdac7f"

      def install
        bin.install "tennis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/tennis/releases/download/v0.1.0/tennis_0.1.0_linux_amd64.tar.gz"
      sha256 "683b937e9f6e190b822cc344890f7b3a79f6d78f6a877da0bfcfd7a3f97d1171"
      def install
        bin.install "tennis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurgeous/tennis/releases/download/v0.1.0/tennis_0.1.0_linux_arm64.tar.gz"
      sha256 "ab21ec16178b0621f45e93b033a4b0285c1b4fd52c30730510f50500a5be5524"
      def install
        bin.install "tennis"
      end
    end
  end

  test do
    system "./tennis --version"
  end
end
