# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vectro < Formula
  desc "TODO"
  homepage "TODO"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_darwin_amd64.tar.gz"
      sha256 "2ae5690d8c475fbfa6fdc276f292d818efd90796cafa0360a0ce0ec4fe1d4b27"

      def install
        bin.install "vectro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_darwin_arm64.tar.gz"
      sha256 "077b314d7531824723522731cc4a35c34d308bb29eb7313320931a8e21cfcfc7"

      def install
        bin.install "vectro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_linux_amd64.tar.gz"
        sha256 "36ef8a89f8c4c3a7d7aaff4b63180fed8695276daf7624c43ea165c8b7dd2e97"

        def install
          bin.install "vectro"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_linux_arm64.tar.gz"
        sha256 "2eaba35047c4a727f55e810f78dae4a4c71ccaf47ea92b7b61d7ffb51a5b2643"

        def install
          bin.install "vectro"
        end
      end
    end
  end

  test do
    system "#{bin}/vectro version"
  end
end
