# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vectro < Formula
  desc "The rpn calculator for your terminal."
  homepage "https://github.com/gurgeous/vectro"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_darwin_amd64.tar.gz"
      sha256 "2ae8e04d52db646140720293a5f6c792ea94a59a6ecdada2d074eb8d98b48aa5"

      def install
        bin.install "vectro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_darwin_arm64.tar.gz"
      sha256 "46f88020afc7c5bf741329819a1cb23878634fd00d7ef48c4b63470b2d045e99"

      def install
        bin.install "vectro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_linux_amd64.tar.gz"
        sha256 "9475fa7ea88f8082546bfdd92039354c64bfe6bb58bcf434d3ebc50e166626e5"

        def install
          bin.install "vectro"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_linux_arm64.tar.gz"
        sha256 "7fd3494237c3918d69ace975dd97f3c1206dbe523d16b2714096b1e8e52ae802"

        def install
          bin.install "vectro"
        end
      end
    end
  end

  test do
    system "#{bin}/vectro --version"
  end
end
