# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vectro < Formula
  desc "The rpn calculator for your terminal."
  homepage "https://github.com/gurgeous/vectro"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_darwin_amd64.tar.gz"
      sha256 "dde206df485864217ed78cab8b02dc225a715b42b024686655365c565f1307a6"

      def install
        bin.install "vectro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_darwin_arm64.tar.gz"
      sha256 "2d7919f22fa9411a78ddf24f0f7badd871cd16adb3bc3ccdb3c144ffe3d34de1"

      def install
        bin.install "vectro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_linux_amd64.tar.gz"
        sha256 "b58afbfd485914bd908dad53db2cefcda568481f9bb36e9b1424e033394773a6"

        def install
          bin.install "vectro"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gurgeous/vectro/releases/download/0.1.0/vectro_0.1.0_linux_arm64.tar.gz"
        sha256 "5159ea3ba6c1b29cacdb2c9ba3ed177869e43ff21a28611d1ddfc7e7b7067194"

        def install
          bin.install "vectro"
        end
      end
    end
  end

  test do
    system "#{bin}/vectro --version"
  end
end
