# This file was generated by GoReleaser. DO NOT EDIT.
cask "tennis" do
  name "tennis"
  desc "Stylish CSV tables in your terminal."
  homepage "https://github.com/gurgeous/tennis#readme"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tennis"
  bash_completion "completions/tennis.bash"
  zsh_completion "completions/_tennis"

  on_macos do
    on_intel do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-darwin-amd64.tar.gz"
      sha256 "ec2a1ca03378ca4a784c12e0552971dfe489a97ea95bc1d5cc5b644f89c4f71d"
    end
    on_arm do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-darwin-arm64.tar.gz"
      sha256 "77c1f07ea09da92f9a94104ac195c8c658c10d29f130dca08583a2e973917aa0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-linux-amd64.tar.gz"
      sha256 "61a897edcd1f59a67e9d5d3692d3429e5de2239f666f5c41d379571f0d68c690"
    end
    on_arm do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-linux-arm64.tar.gz"
      sha256 "8c2986a318d586de1155af2b0efe7f68e04dfab684750adafd66fd1edd2645a5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tennis"]
    end
  end

  # No zap stanza required
end
