# This file was generated by GoReleaser. DO NOT EDIT.
cask "tennis" do
  name "tennis"
  desc "Stylish CSV tables in your terminal."
  homepage "https://github.com/gurgeous/tennis#readme"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tennis"
  bash_completion "completions/tennis.bash"
  zsh_completion "completions/_tennis"

  on_macos do
    on_intel do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-darwin-amd64.tar.gz"
      sha256 "09c5e2679bec23d05fe91ef3e1f2fc0d5f847d26db81e1126d1a69251253c962"
    end
    on_arm do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-darwin-arm64.tar.gz"
      sha256 "0ce5f67f5588905613c6f9e0041b7884820b1387082da20e274d46219e8e2a30"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-linux-amd64.tar.gz"
      sha256 "33adb3f77f40e0ff691f225c3a7b074c1b7048e657c58a6a3b82ad6b94290e63"
    end
    on_arm do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-linux-arm64.tar.gz"
      sha256 "d53d6d9e6a32ebc5dde22cb217d635f688b65ec20cac360d430038b1c2d3d712"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tennis"]
    end
  end

  # No zap stanza required
end
